-- Autostart Processes
hl.on("hyprland.start", function()
    hl.exec_cmd("/home/lenin/Downloads/Wallpapers/restore-wallpaper.fish")
    hl.exec_cmd("waybar &")
    hl.exec_cmd("fcitx5 -d &")
    hl.exec_cmd("mako &")
    hl.exec_cmd("nm-applet --indicator &")
    hl.exec_cmd("bash -c \"mkfifo /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob && tail -f /tmp/$HYPRLAND_INSTANCE_SIGNATURE.wob | wob & disown\" &")
    hl.exec_cmd("/usr/lib/polkit-kde-authentication-agent-1 &")
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("wl-paste --type text --watch cliphist store &")
    hl.exec_cmd("wl-paste --type image --watch cliphist store &")
    hl.exec_cmd("systemctl --user import-environment &")
end)
